/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_billthefarmer_mididriver_MidiDriver */

#ifndef _Included_org_billthefarmer_mididriver_MidiDriver
#define _Included_org_billthefarmer_mididriver_MidiDriver
#ifdef __cplusplus
extern "C" {
#endif
#undef org_billthefarmer_mididriver_MidiDriver_SAMPLE_RATE
#define org_billthefarmer_mididriver_MidiDriver_SAMPLE_RATE 22050L
#undef org_billthefarmer_mididriver_MidiDriver_BUFFER_SIZE
#define org_billthefarmer_mididriver_MidiDriver_BUFFER_SIZE 4096L
/*
 * Class:     org_billthefarmer_mididriver_MidiDriver
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_billthefarmer_mididriver_MidiDriver_init
  (JNIEnv *, jobject);

/*
 * Class:     org_billthefarmer_mididriver_MidiDriver
 * Method:    config
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_org_billthefarmer_mididriver_MidiDriver_config
  (JNIEnv *, jobject);

/*
 * Class:     org_billthefarmer_mididriver_MidiDriver
 * Method:    render
 * Signature: ([S)I
 */
JNIEXPORT jint JNICALL Java_org_billthefarmer_mididriver_MidiDriver_render
  (JNIEnv *, jobject, jshortArray);

/*
 * Class:     org_billthefarmer_mididriver_MidiDriver
 * Method:    write
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_org_billthefarmer_mididriver_MidiDriver_write
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_billthefarmer_mididriver_MidiDriver
 * Method:    shutdown
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_billthefarmer_mididriver_MidiDriver_shutdown
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
